version: '3.9'

services:
  backend:
    container_name: eventos-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:443"  # HTTPS
      - "8000:80"   # HTTP (opcional)
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      eventos_net:
        ipv4_address: 192.168.251.10
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - .:/var/www/html
      - ./nginx/002-eventosng.conf:/etc/nginx/sites-available/default
      - /etc/ssl/unibague:/etc/ssl/unibague:ro
    command: >
      sh -c "sleep 10 && php artisan migrate --force && service php8.2-fpm start && nginx -g 'daemon off;'"

  postgres:
    image: postgres:15-alpine
    container_name: eventos-postgres
    environment:
      POSTGRES_DB: eventos_unibague
      POSTGRES_USER: desarrollador
      POSTGRES_PASSWORD: 'Ed?3p20DB23'
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      eventos_net:
        ipv4_address: 192.168.251.12

networks:
  eventos_net:
    external: true

volumes:
  pgdata:
