services:
  backend:
    container_name: eventos-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:443"  # HTTPS externo mapeado
      - "8010:80"   # HTTP externo mapeado
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      eventos_net:
        ipv4_address: 192.168.251.10
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - .:/var/www/html
      - ./nginx/002-eventosng.conf:/etc/nginx/sites-available/default
      - ./STAR_unibague_edu_co.crt:/etc/ssl/unibague/STAR_unibague_edu_co.crt:ro
      - ./STAR_unibague_edu_co.ca-bundle:/etc/ssl/unibague/STAR_unibague_edu_co.ca-bundle:ro
      - ./unibague_edu_co.pem:/etc/ssl/unibague/unibague_edu_co.pem:ro
    command: >
      sh -c "sleep 10 && php artisan migrate --force && nginx -g 'daemon off;'"

  postgres:
    image: postgres:15-alpine
    container_name: eventos-postgres
    environment:
      POSTGRES_DB: eventos_unibague
      POSTGRES_USER: desarrollador
      POSTGRES_PASSWORD: 'Ed?3p20DB23'
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      eventos_net:
        ipv4_address: 192.168.251.12

networks:
  eventos_net:
    external: true

volumes:
  pgdata:
